name: Build and deploy Python app to Azure Web App - stock-market-assistant-fastapi-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create virtual environment and install dependencies
        run: |
          cd backend
          python -m venv venv              
          source venv/bin/activate         
          pip install -r ../requirements.txt 

      - name: Zip backend only
        run: |
          cd backend
          zip -r ../release.zip .             # ← zip only backend contents

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'stock-market-assistant-fastapi-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BB390D93B37B4000A1DF71DFFBB7F6F1 }}